### ISSUE TITLE
SliderPath's positionAt() ignores slider repeats

### ISSUE THREAD

**Issue by cunev** [kionell/osu-classes#6]
SliderPath's positionAt(progress) seems to give out the position ignoring the slider's repeats.

I'm not sure if this is a bug, or it needs to be handled by me.
On a slider with 1 repeat, progress 0.5 should give the end position of the slider - but it returns the middle position.

**Comment by cunev** [comment]
wrong repo!

**Comment by kionell** [comment]
> positionAt(progress) seems to give out the position ignoring the slider's repeats.

Yeah, it works as intended. positionAt() returns relative position of a path (for a single span). You need to use curvePositionAt() to get total progress of a slidable object.

**Comment by cunev** [comment]
Thanks!
